	</div>
	<div class="footer">
		<a href="http://www.kuipp.com/index.php" class="footer">Home</a>&nbsp;&nbsp;&nbsp;&bull;&nbsp;&nbsp;
		<a href="http://www.kuipp.com/what.php" class="footer">What is Kuipp?</a>&nbsp;&nbsp;&nbsp;&bull;&nbsp;&nbsp;
		<a href="http://itunes.apple.com/us/app/kuipp/id436731294?mt=8" class="footer">Get Kuipp!</a>&nbsp;&nbsp;&nbsp;&bull;&nbsp;&nbsp;
		<a href="http://www.kuipp.com/about.php" class="footer">About Us</a>&nbsp;&nbsp;&nbsp;&bull;&nbsp;&nbsp;
		<a href="http://www.kuipp.com/contact.php" class="footer">Contacts</a>&nbsp;&nbsp;&nbsp;&bull;&nbsp;&nbsp;
		<a href="http://www.kuipp.com/blog/" class="footer">Blog</a>&nbsp;&nbsp;&nbsp;&bull;&nbsp;&nbsp;
		<a href="http://www.kuipp.com/terms.php" class="footer">Terms of Use</a>&nbsp;&nbsp;&nbsp;&bull;&nbsp;&nbsp;
		<a href="http://www.kuipp.com/policy.php" class="footer">Privacy Policy</a><br>
		<hr class="footer">
		<font class="copyright">&copy; 2011 Kuipp LLC</font>
	</div>
</div>
</body>
</html>