<html>
<head>
<title>Kuipp - <?php echo("$siteTitle"); ?></title>
<link rel="stylesheet" type="text/css" href="http://www.kuipp.com/stylesheet.css">
<meta name="description" content="Kuipp (pronounced like the word 'quip') is a mobile Q&A platform that provides users with a fun, fast way to ask and answer questions to discover what's currently happening in a specific area.  Download the iPhone app to learn about your local community!">
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<link rel="image_src" href="http://www.kuipp.com/kuipp_logo_square.jpg" />
</head>
<body>

<div class="wrap">
	<div class="header">
		<div class="header-left">
			<a href="http://www.kuipp.com/what.php" class="header">What is Kuipp?</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<a href="http://itunes.apple.com/us/app/kuipp/id436731294?mt=8" class="header">Get Kuipp!</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<a href="http://www.kuipp.com/about.php" class="header">About Us</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<a href="http://www.kuipp.com/blog/" class="header">Blog</a>
		</div>
		<div class="header-right">
		Follow us on: <a href="http://www.facebook.com/Kuipp">Facebook</a> | <a href="http://www.twitter.com/#!/KuippTeam">Twitter</a>
		</div>
	</div>
</div>

<div class="main">
	<div class="logo">
		<img src="http://www.kuipp.com/logo-background.jpg" alt="Logo" usemap ="#logo" class="logo">
			<map name="logo">
			<area shape="rect" coords="5,75,250,170" href="http://www.kuipp.com/index.php" alt="Home">
			</map>
		</div>
	<div class="body">
